# Generated by Django 5.2.1 on 2025-06-08 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('report_format', models.CharField(choices=[('PDF', 'PDF'), ('HTML', 'HTML'), ('BOTH', 'Both')], default='BOTH', max_length=5)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('pdf_path', models.CharField(blank=True, max_length=255, null=True)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Delivery',
                'verbose_name_plural': 'Report Deliveries',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'report_date'], name='notificatio_user_id_0ba6c7_idx'), models.Index(fields=['status'], name='notificatio_status_05f9e0_idx')],
            },
        ),
    ]
