# Generated by Django 5.2.1 on 2025-06-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='format',
            field=models.CharField(choices=[('PDF', 'PDF Only'), ('HTML', 'HTML Only'), ('BOTH', 'Both PDF and HTML')], default='BOTH', max_length=5),
        ),
    ]
